name: Publish Code Server Tools CLI

on:
  push:
    branches: [main]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore

      - name: Publish
        run: dotnet publish CodeServerTools.CLI/CodeServerTools.CLI.csproj -c Release -o release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CodeServerTools_CLI_Artifact
          path: /home/runner/work/CodeServerTools.CLI/CodeServerTools.CLI/release/